# fly.toml app configuration file generated for hasen-backend on 2026-04-15T10:58:50+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hasen-backend'
primary_region = 'fra'

[build]
  dockerfile = 'Dockerfile'

[deploy]
  strategy = 'immediate'

[env]
  NODE_ENV = 'production'
  PORT = '3001'

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 1
  processes = ['app']
  
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 800

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/api/health'
    protocol = 'http'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
