export { provideAnimationCoords, useAnimationCoords } from './composables/useAnimationCoords'
export { useDealAnimation } from './composables/useDealAnimation'
export { useCardAnimation } from './composables/useCardAnimation'
export type { AnimatedCard } from './composables/useDealAnimation'
export type { AnimationCoords } from './composables/useAnimationCoords'
